version: "3.7"

services: 
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentx_network

  app:
    build: .
    container_name: rentx
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - rentx_network
    #links:
     # - database_ignite
    depends_on:
      - database_ignite

volumes:
  pgdata:
    driver: local

networks:
  rentx_network:
    driver: bridge